-- Code generated by fin-protoc. DO NOT EDIT.


local rc_binary_proto = Proto("RcBinary", "RcBinary Protocol")
local fields = {
    -- Field from RcBinary
    rc_binary_msg_type = ProtoField.uint32("rc_binary.msg_type", "MsgType", base.DEC),
    rc_binary_version = ProtoField.uint32("rc_binary.version", "Version", base.DEC),
    rc_binary_msg_body_len = ProtoField.uint32("rc_binary.msg_body_len", "MsgBodyLen", base.DEC),
    -- Unsupported type: match
    -- Field from NewOrder
    new_order_cl_ord_id = ProtoField.string("new_order.cl_ord_id", "ClOrdID"),
    new_order_security_id = ProtoField.string("new_order.security_id", "SecurityID"),
    new_order_side = ProtoField.char("new_order.side", "Side", base.OCT),
    new_order_price = ProtoField.uint64("new_order.price", "Price", base.DEC),
    new_order_order_qty = ProtoField.uint64("new_order.order_qty", "OrderQty", base.DEC),
    new_order_ord_type = ProtoField.char("new_order.ord_type", "OrdType", base.OCT),
    new_order_account = ProtoField.string("new_order.account", "Account"),
    -- Field from OrderConfirm
    order_confirm_cl_ord_id = ProtoField.string("order_confirm.cl_ord_id", "ClOrdID"),
    order_confirm_exec_type = ProtoField.char("order_confirm.exec_type", "ExecType", base.OCT),
    order_confirm_ord_rej_reason = ProtoField.uint32("order_confirm.ord_rej_reason", "OrdRejReason", base.DEC),
    order_confirm_ord_cnfm_id = ProtoField.string("order_confirm.ord_cnfm_id", "OrdCnfmID"),
    -- Field from ExecutionReport
    execution_report_cl_ord_id = ProtoField.string("execution_report.cl_ord_id", "ClOrdID"),
    execution_report_ord_cnfm_id = ProtoField.string("execution_report.ord_cnfm_id", "OrdCnfmID"),
    execution_report_last_px = ProtoField.uint64("execution_report.last_px", "LastPx", base.DEC),
    execution_report_last_qty = ProtoField.uint64("execution_report.last_qty", "LastQty", base.DEC),
    execution_report_ord_status = ProtoField.char("execution_report.ord_status", "OrdStatus", base.OCT),
    -- Field from OrderCancel
    order_cancel_cl_ord_id = ProtoField.string("order_cancel.cl_ord_id", "ClOrdID"),
    order_cancel_orig_cl_ord_id = ProtoField.string("order_cancel.orig_cl_ord_id", "OrigClOrdID"),
    order_cancel_security_id = ProtoField.string("order_cancel.security_id", "SecurityID"),
    -- Field from CancelReject
    cancel_reject_cl_ord_id = ProtoField.string("cancel_reject.cl_ord_id", "ClOrdID"),
    cancel_reject_orig_cl_ord_id = ProtoField.string("cancel_reject.orig_cl_ord_id", "OrigClOrdID"),
    cancel_reject_cxl_rej_reason = ProtoField.uint32("cancel_reject.cxl_rej_reason", "CxlRejReason", base.DEC),
}

for _, field in pairs(fields) do
    rc_binary_proto.fields[field] = field
end

local function dissect_new_order(buf, pinfo, tree, offset)
    local subtree = tree:add(rc_binary_proto, buf(offset, 1), "NewOrder")
    local new_order_cl_ord_id_len = buf(offset, 4):uint()
    subtree:add("ClOrdID Len: ".. new_order_cl_ord_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.new_order_cl_ord_id, buf(offset, new_order_cl_ord_id_len))
    offset = offset + new_order_cl_ord_id_len
    local new_order_security_id_len = buf(offset, 4):uint()
    subtree:add("SecurityID Len: ".. new_order_security_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.new_order_security_id, buf(offset, new_order_security_id_len))
    offset = offset + new_order_security_id_len
    subtree:add(fields.new_order_side, buf(offset, 1))
    offset = offset + 1
    subtree:add(fields.new_order_price, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.new_order_order_qty, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.new_order_ord_type, buf(offset, 1))
    offset = offset + 1
    local new_order_account_len = buf(offset, 4):uint()
    subtree:add("Account Len: ".. new_order_account_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.new_order_account, buf(offset, new_order_account_len))
    offset = offset + new_order_account_len
    return offset
end


local function dissect_order_confirm(buf, pinfo, tree, offset)
    local subtree = tree:add(rc_binary_proto, buf(offset, 1), "OrderConfirm")
    local order_confirm_cl_ord_id_len = buf(offset, 4):uint()
    subtree:add("ClOrdID Len: ".. order_confirm_cl_ord_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.order_confirm_cl_ord_id, buf(offset, order_confirm_cl_ord_id_len))
    offset = offset + order_confirm_cl_ord_id_len
    subtree:add(fields.order_confirm_exec_type, buf(offset, 1))
    offset = offset + 1
    subtree:add(fields.order_confirm_ord_rej_reason, buf(offset, 4))
    offset = offset + 4
    local order_confirm_ord_cnfm_id_len = buf(offset, 4):uint()
    subtree:add("OrdCnfmID Len: ".. order_confirm_ord_cnfm_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.order_confirm_ord_cnfm_id, buf(offset, order_confirm_ord_cnfm_id_len))
    offset = offset + order_confirm_ord_cnfm_id_len
    return offset
end


local function dissect_execution_report(buf, pinfo, tree, offset)
    local subtree = tree:add(rc_binary_proto, buf(offset, 1), "ExecutionReport")
    local execution_report_cl_ord_id_len = buf(offset, 4):uint()
    subtree:add("ClOrdID Len: ".. execution_report_cl_ord_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.execution_report_cl_ord_id, buf(offset, execution_report_cl_ord_id_len))
    offset = offset + execution_report_cl_ord_id_len
    local execution_report_ord_cnfm_id_len = buf(offset, 4):uint()
    subtree:add("OrdCnfmID Len: ".. execution_report_ord_cnfm_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.execution_report_ord_cnfm_id, buf(offset, execution_report_ord_cnfm_id_len))
    offset = offset + execution_report_ord_cnfm_id_len
    subtree:add(fields.execution_report_last_px, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.execution_report_last_qty, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.execution_report_ord_status, buf(offset, 1))
    offset = offset + 1
    return offset
end


local function dissect_order_cancel(buf, pinfo, tree, offset)
    local subtree = tree:add(rc_binary_proto, buf(offset, 1), "OrderCancel")
    local order_cancel_cl_ord_id_len = buf(offset, 4):uint()
    subtree:add("ClOrdID Len: ".. order_cancel_cl_ord_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.order_cancel_cl_ord_id, buf(offset, order_cancel_cl_ord_id_len))
    offset = offset + order_cancel_cl_ord_id_len
    local order_cancel_orig_cl_ord_id_len = buf(offset, 4):uint()
    subtree:add("OrigClOrdID Len: ".. order_cancel_orig_cl_ord_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.order_cancel_orig_cl_ord_id, buf(offset, order_cancel_orig_cl_ord_id_len))
    offset = offset + order_cancel_orig_cl_ord_id_len
    local order_cancel_security_id_len = buf(offset, 4):uint()
    subtree:add("SecurityID Len: ".. order_cancel_security_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.order_cancel_security_id, buf(offset, order_cancel_security_id_len))
    offset = offset + order_cancel_security_id_len
    return offset
end


local function dissect_cancel_reject(buf, pinfo, tree, offset)
    local subtree = tree:add(rc_binary_proto, buf(offset, 1), "CancelReject")
    local cancel_reject_cl_ord_id_len = buf(offset, 4):uint()
    subtree:add("ClOrdID Len: ".. cancel_reject_cl_ord_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.cancel_reject_cl_ord_id, buf(offset, cancel_reject_cl_ord_id_len))
    offset = offset + cancel_reject_cl_ord_id_len
    local cancel_reject_orig_cl_ord_id_len = buf(offset, 4):uint()
    subtree:add("OrigClOrdID Len: ".. cancel_reject_orig_cl_ord_id_len, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.cancel_reject_orig_cl_ord_id, buf(offset, cancel_reject_orig_cl_ord_id_len))
    offset = offset + cancel_reject_orig_cl_ord_id_len
    subtree:add(fields.cancel_reject_cxl_rej_reason, buf(offset, 4))
    offset = offset + 4
    return offset
end


function rc_binary_proto.dissector(buf, pinfo, tree)
    pinfo.cols.protocol = "rc_binary"
    local offset = 0
    local msg_type = buf(offset, 4):uint()
    tree:add(fields.rc_binary_msg_type, buf(offset, 4))
    offset = offset + 4
    tree:add(fields.rc_binary_version, buf(offset, 4))
    offset = offset + 4
    tree:add(fields.rc_binary_msg_body_len, buf(offset, 4))
    offset = offset + 4
    if msg_type == 100101 then -- NewOrder
        dissect_new_order(buf, pinfo, tree, offset)
        pinfo.cols.info:set("NewOrder")
    elseif msg_type == 200102 then -- OrderConfirm
        dissect_order_confirm(buf, pinfo, tree, offset)
        pinfo.cols.info:set("OrderConfirm")
    elseif msg_type == 200115 then -- ExecutionReport
        dissect_execution_report(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExecutionReport")
    elseif msg_type == 190007 then -- OrderCancel
        dissect_order_cancel(buf, pinfo, tree, offset)
        pinfo.cols.info:set("OrderCancel")
    elseif msg_type == 290008 then -- CancelReject
        dissect_cancel_reject(buf, pinfo, tree, offset)
        pinfo.cols.info:set("CancelReject")
    end
end


local tcp_table = DissectorTable.get("tcp.port")
tcp_table:add(8080, rc_binary_proto)
