-- Code generated by fin-protoc. DO NOT EDIT.


local root_packet_proto = Proto("RootPacket", "RootPacket Protocol")
local fields = {
    -- Field from RootPacket
    root_packet_msg_type = ProtoField.uint32("root_packet.msg_type", "MsgType", base.DEC),
    root_packet_payload_len = ProtoField.uint32("root_packet.payload_len", "PayloadLen", base.DEC),
    -- Unsupported type: match
    root_packet_checksum = ProtoField.int("root_packet.checksum", "Checksum", base.DEC),
    -- Field from BasicPacket
    basic_packet_field_i_8 = ProtoField.int("basic_packet.field_i_8", "fieldI8", base.DEC),
    basic_packet_field_i_16 = ProtoField.int("basic_packet.field_i_16", "fieldI16", base.DEC),
    basic_packet_field_i_32 = ProtoField.int("basic_packet.field_i_32", "fieldI32", base.DEC),
    basic_packet_field_i_64 = ProtoField.int64("basic_packet.field_i_64", "fieldI64", base.DEC),
    basic_packet_field_char = ProtoField.char("basic_packet.field_char", "fieldChar", base.OCT),
    basic_packet_field_u_8 = ProtoField.uint32("basic_packet.field_u_8", "fieldU8", base.DEC),
    basic_packet_field_u_16 = ProtoField.uint32("basic_packet.field_u_16", "fieldU16", base.DEC),
    basic_packet_field_u_32 = ProtoField.uint32("basic_packet.field_u_32", "fieldU32", base.DEC),
    basic_packet_field_u_64 = ProtoField.uint64("basic_packet.field_u_64", "fieldU64", base.DEC),
    basic_packet_field_f_32 = ProtoField.float("basic_packet.field_f_32", "fieldF32", base.DEC),
    basic_packet_field_f_64 = ProtoField.double("basic_packet.field_f_64", "fieldF64", base.DEC),
    basic_packet_field_i_8_list = ProtoField.int("basic_packet.field_i_8_list", "fieldI8List", base.DEC),
    basic_packet_field_i_16_list = ProtoField.int("basic_packet.field_i_16_list", "fieldI16List", base.DEC),
    basic_packet_field_i_32_list = ProtoField.int("basic_packet.field_i_32_list", "fieldI32List", base.DEC),
    basic_packet_field_i_64_list = ProtoField.int64("basic_packet.field_i_64_list", "fieldI64List", base.DEC),
    basic_packet_field_char_list = ProtoField.char("basic_packet.field_char_list", "fieldCharList", base.OCT),
    basic_packet_field_u_8_list = ProtoField.uint32("basic_packet.field_u_8_list", "fieldU8List", base.DEC),
    basic_packet_field_u_16_list = ProtoField.uint32("basic_packet.field_u_16_list", "fieldU16List", base.DEC),
    basic_packet_field_u_32_list = ProtoField.uint32("basic_packet.field_u_32_list", "fieldU32List", base.DEC),
    basic_packet_field_u_64_list = ProtoField.uint64("basic_packet.field_u_64_list", "fieldU64List", base.DEC),
    basic_packet_field_f_32_list = ProtoField.float("basic_packet.field_f_32_list", "fieldF32List", base.DEC),
    basic_packet_field_f_64_list = ProtoField.double("basic_packet.field_f_64_list", "fieldF64List", base.DEC),
    -- Field from StringPacket
    string_packet_field_dynamic_string = ProtoField.string("string_packet.field_dynamic_string", "fieldDynamicString"),
    string_packet_field_dynamic_string_1 = ProtoField.string("string_packet.field_dynamic_string_1", "fieldDynamicString1"),
    string_packet_field_fixed_string_1 = ProtoField.string("string_packet.field_fixed_string_1", "fieldFixedString1"),
    string_packet_field_fixed_string_10 = ProtoField.string("string_packet.field_fixed_string_10", "fieldFixedString10"),
    string_packet_field_dynamic_string_list = ProtoField.string("string_packet.field_dynamic_string_list", "fieldDynamicStringList"),
    string_packet_field_dynamic_string_1_list = ProtoField.string("string_packet.field_dynamic_string_1_list", "fieldDynamicString1List"),
    string_packet_field_fixed_string_1_list = ProtoField.string("string_packet.field_fixed_string_1_list", "fieldFixedString1List"),
    string_packet_field_fixed_string_10_list = ProtoField.string("string_packet.field_fixed_string_10_list", "fieldFixedString10List"),
    -- Field from NestedPacket
    -- Field from SubPacket
    sub_packet_field_u_32 = ProtoField.uint32("sub_packet.field_u_32", "fieldU32", base.DEC),
    sub_packet_field_i_16_list = ProtoField.int("sub_packet.field_i_16_list", "fieldI16List", base.DEC),
    -- Unsupported type: SubPacket
    -- Field from InerPacket
    iner_packet_field_u_32 = ProtoField.uint32("iner_packet.field_u_32", "fieldU32", base.DEC),
    iner_packet_field_i_16_list = ProtoField.int("iner_packet.field_i_16_list", "fieldI16List", base.DEC),
    -- Field from SubPacket
    sub_packet_field_u_32 = ProtoField.uint32("sub_packet.field_u_32", "fieldU32", base.DEC),
    sub_packet_field_i_16_list = ProtoField.int("sub_packet.field_i_16_list", "fieldI16List", base.DEC),
    -- Field from EmptyPacket
}

for _, field in pairs(fields) do
    root_packet_proto.fields[field] = field
end

local function dissect_basic_packet(buf, pinfo, tree, offset)
    local subtree = tree:add(root_packet_proto, buf(offset, 1), "BasicPacket")
    subtree:le_add(fields.basic_packet_field_i_8, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.basic_packet_field_i_16, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.basic_packet_field_i_32, buf(offset, 4))
    offset = offset + 4
    subtree:le_add(fields.basic_packet_field_i_64, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.basic_packet_field_char, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.basic_packet_field_u_8, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.basic_packet_field_u_16, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.basic_packet_field_u_32, buf(offset, 4))
    offset = offset + 4
    subtree:le_add(fields.basic_packet_field_u_64, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.basic_packet_field_f_32, buf(offset, 4))
    offset = offset + 4
    subtree:le_add(fields.basic_packet_field_f_64, buf(offset, 8))
    offset = offset + 8
    local basic_packet_field_i_8_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldI8List Size: ".. basic_packet_field_i_8_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_i_8_list_size do
        subtree:le_add(fields.basic_packet_field_i_8_list, buf(offset, 1))
        offset = offset + 1
        pinfo.cols.info:append(" fieldI8List["..i.."]")
    end
    local basic_packet_field_i_16_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldI16List Size: ".. basic_packet_field_i_16_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_i_16_list_size do
        subtree:le_add(fields.basic_packet_field_i_16_list, buf(offset, 2))
        offset = offset + 2
        pinfo.cols.info:append(" fieldI16List["..i.."]")
    end
    local basic_packet_field_i_32_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldI32List Size: ".. basic_packet_field_i_32_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_i_32_list_size do
        subtree:le_add(fields.basic_packet_field_i_32_list, buf(offset, 4))
        offset = offset + 4
        pinfo.cols.info:append(" fieldI32List["..i.."]")
    end
    local basic_packet_field_i_64_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldI64List Size: ".. basic_packet_field_i_64_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_i_64_list_size do
        subtree:le_add(fields.basic_packet_field_i_64_list, buf(offset, 8))
        offset = offset + 8
        pinfo.cols.info:append(" fieldI64List["..i.."]")
    end
    local basic_packet_field_char_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldCharList Size: ".. basic_packet_field_char_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_char_list_size do
        subtree:le_add(fields.basic_packet_field_char_list, buf(offset, 1))
        offset = offset + 1
        pinfo.cols.info:append(" fieldCharList["..i.."]")
    end
    local basic_packet_field_u_8_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldU8List Size: ".. basic_packet_field_u_8_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_u_8_list_size do
        subtree:le_add(fields.basic_packet_field_u_8_list, buf(offset, 1))
        offset = offset + 1
        pinfo.cols.info:append(" fieldU8List["..i.."]")
    end
    local basic_packet_field_u_16_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldU16List Size: ".. basic_packet_field_u_16_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_u_16_list_size do
        subtree:le_add(fields.basic_packet_field_u_16_list, buf(offset, 2))
        offset = offset + 2
        pinfo.cols.info:append(" fieldU16List["..i.."]")
    end
    local basic_packet_field_u_32_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldU32List Size: ".. basic_packet_field_u_32_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_u_32_list_size do
        subtree:le_add(fields.basic_packet_field_u_32_list, buf(offset, 4))
        offset = offset + 4
        pinfo.cols.info:append(" fieldU32List["..i.."]")
    end
    local basic_packet_field_u_64_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldU64List Size: ".. basic_packet_field_u_64_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_u_64_list_size do
        subtree:le_add(fields.basic_packet_field_u_64_list, buf(offset, 8))
        offset = offset + 8
        pinfo.cols.info:append(" fieldU64List["..i.."]")
    end
    local basic_packet_field_f_32_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldF32List Size: ".. basic_packet_field_f_32_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_f_32_list_size do
        subtree:le_add(fields.basic_packet_field_f_32_list, buf(offset, 4))
        offset = offset + 4
        pinfo.cols.info:append(" fieldF32List["..i.."]")
    end
    local basic_packet_field_f_64_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldF64List Size: ".. basic_packet_field_f_64_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,basic_packet_field_f_64_list_size do
        subtree:le_add(fields.basic_packet_field_f_64_list, buf(offset, 8))
        offset = offset + 8
        pinfo.cols.info:append(" fieldF64List["..i.."]")
    end
    return offset
end


local function dissect_string_packet(buf, pinfo, tree, offset)
    local subtree = tree:add(root_packet_proto, buf(offset, 1), "StringPacket")
    local string_packet_field_dynamic_string_len = buf(offset, 2):le_uint()
    subtree:add("fieldDynamicString Len: ".. string_packet_field_dynamic_string_len, buf(offset, 2))
    offset = offset + 2
    subtree:add(fields.string_packet_field_dynamic_string, buf(offset, string_packet_field_dynamic_string_len))
    offset = offset + string_packet_field_dynamic_string_len
    local string_packet_field_dynamic_string_1_len = buf(offset, 2):le_uint()
    subtree:add("fieldDynamicString1 Len: ".. string_packet_field_dynamic_string_1_len, buf(offset, 2))
    offset = offset + 2
    subtree:add(fields.string_packet_field_dynamic_string_1, buf(offset, string_packet_field_dynamic_string_1_len))
    offset = offset + string_packet_field_dynamic_string_1_len
    subtree:add(fields.string_packet_field_fixed_string_1, buf(offset, 1))
    offset = offset + 1
    subtree:add(fields.string_packet_field_fixed_string_10, buf(offset, 10))
    offset = offset + 10
    local string_packet_field_dynamic_string_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldDynamicStringList Size: ".. string_packet_field_dynamic_string_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,string_packet_field_dynamic_string_list_size do
        local string_packet_field_dynamic_string_list_len = buf(offset, 2):le_uint()
        subtree:add("fieldDynamicStringList Len: ".. string_packet_field_dynamic_string_list_len, buf(offset, 2))
        offset = offset + 2
        subtree:add(fields.string_packet_field_dynamic_string_list, buf(offset, string_packet_field_dynamic_string_list_len))
        offset = offset + string_packet_field_dynamic_string_list_len
        pinfo.cols.info:append(" fieldDynamicStringList["..i.."]")
    end
    local string_packet_field_dynamic_string_1_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldDynamicString1List Size: ".. string_packet_field_dynamic_string_1_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,string_packet_field_dynamic_string_1_list_size do
        local string_packet_field_dynamic_string_1_list_len = buf(offset, 2):le_uint()
        subtree:add("fieldDynamicString1List Len: ".. string_packet_field_dynamic_string_1_list_len, buf(offset, 2))
        offset = offset + 2
        subtree:add(fields.string_packet_field_dynamic_string_1_list, buf(offset, string_packet_field_dynamic_string_1_list_len))
        offset = offset + string_packet_field_dynamic_string_1_list_len
        pinfo.cols.info:append(" fieldDynamicString1List["..i.."]")
    end
    local string_packet_field_fixed_string_1_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldFixedString1List Size: ".. string_packet_field_fixed_string_1_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,string_packet_field_fixed_string_1_list_size do
        subtree:add(fields.string_packet_field_fixed_string_1_list, buf(offset, 1))
        offset = offset + 1
        pinfo.cols.info:append(" fieldFixedString1List["..i.."]")
    end
    local string_packet_field_fixed_string_10_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldFixedString10List Size: ".. string_packet_field_fixed_string_10_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,string_packet_field_fixed_string_10_list_size do
        subtree:add(fields.string_packet_field_fixed_string_10_list, buf(offset, 10))
        offset = offset + 10
        pinfo.cols.info:append(" fieldFixedString10List["..i.."]")
    end
    return offset
end


local function dissect_iner_packet(buf, pinfo, tree, offset)
    local subtree = tree:add(root_packet_proto, buf(offset, 1), "InerPacket")
    subtree:le_add(fields.iner_packet_field_u_32, buf(offset, 4))
    offset = offset + 4
    local iner_packet_field_i_16_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldI16List Size: ".. iner_packet_field_i_16_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,iner_packet_field_i_16_list_size do
        subtree:le_add(fields.iner_packet_field_i_16_list, buf(offset, 2))
        offset = offset + 2
        pinfo.cols.info:append(" fieldI16List["..i.."]")
    end
    return offset
end

local function dissect_nested_packet(buf, pinfo, tree, offset)
    local subtree = tree:add(root_packet_proto, buf(offset, 1), "NestedPacket")
    -- unsupported type: SubPacket
    
    local nested_packet_sub_packet_list_size = buf(offset, 2):le_uint()
    subtree:add("SubPacketList Size: ".. nested_packet_sub_packet_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,nested_packet_sub_packet_list_size do
        -- unsupported type: SubPacket
        
        pinfo.cols.info:append(" SubPacketList["..i.."]")
    end
    dissect_iner_packet(buf, pinfo, subtree, offset)
    pinfo.cols.info:set("InerPacket")
    return offset
end


local function dissect_sub_packet(buf, pinfo, tree, offset)
    local subtree = tree:add(root_packet_proto, buf(offset, 1), "SubPacket")
    subtree:le_add(fields.sub_packet_field_u_32, buf(offset, 4))
    offset = offset + 4
    local sub_packet_field_i_16_list_size = buf(offset, 2):le_uint()
    subtree:add("fieldI16List Size: ".. sub_packet_field_i_16_list_size, buf(offset, 2))
    offset = offset + 2
    for i=1,sub_packet_field_i_16_list_size do
        subtree:le_add(fields.sub_packet_field_i_16_list, buf(offset, 2))
        offset = offset + 2
        pinfo.cols.info:append(" fieldI16List["..i.."]")
    end
    return offset
end


local function dissect_empty_packet(buf, pinfo, tree, offset)
    local subtree = tree:add(root_packet_proto, buf(offset, 1), "EmptyPacket")
    subtree:append_text(" (No Body)")
    return offset
end


function root_packet_proto.dissector(buf, pinfo, tree)
    pinfo.cols.protocol = "root_packet"
    local offset = 0
    local msg_type = buf(offset, 2):le_uint()
    tree:le_add(fields.root_packet_msg_type, buf(offset, 2))
    offset = offset + 2
    tree:le_add(fields.root_packet_payload_len, buf(offset, 4))
    offset = offset + 4
    if msg_type == 1 then -- BasicPacket
        dissect_basic_packet(buf, pinfo, tree, offset)
        pinfo.cols.info:set("BasicPacket")
    elseif msg_type == 2 then -- StringPacket
        dissect_string_packet(buf, pinfo, tree, offset)
        pinfo.cols.info:set("StringPacket")
    elseif msg_type == 3 then -- NestedPacket
        dissect_nested_packet(buf, pinfo, tree, offset)
        pinfo.cols.info:set("NestedPacket")
    elseif msg_type == 4 then -- EmptyPacket
        dissect_empty_packet(buf, pinfo, tree, offset)
        pinfo.cols.info:set("EmptyPacket")
    end
    tree:le_add(fields.root_packet_checksum, buf(offset, 4))
    offset = offset + 4
end


local tcp_table = DissectorTable.get("tcp.port")
tcp_table:add(8080, root_packet_proto)
