-- Code generated by fin-protoc. DO NOT EDIT.


local bjse_md_binary_proto = Proto("BjseMdBinary", "BjseMdBinary Protocol")
local fields = {
    -- Field from Logon
    logon_sender_comp_id = ProtoField.string("logon.sender_comp_id", "SenderCompID"),
    logon_target_comp_id = ProtoField.string("logon.target_comp_id", "TargetCompID"),
    logon_heart_bt_int = ProtoField.int("logon.heart_bt_int", "HeartBtInt", base.DEC),
    logon_password = ProtoField.string("logon.password", "Password"),
    logon_default_appl_ver_id = ProtoField.string("logon.default_appl_ver_id", "DefaultApplVerID"),
    -- Field from Logout
    logout_session_status = ProtoField.int("logout.session_status", "SessionStatus", base.DEC),
    logout_text = ProtoField.string("logout.text", "Text"),
    -- Field from Heartbeat
    -- Field from ChannelHeartbeat
    channel_heartbeat_channel_no = ProtoField.uint32("channel_heartbeat.channel_no", "ChannelNo", base.DEC),
    channel_heartbeat_appl_last_seq_num = ProtoField.int64("channel_heartbeat.appl_last_seq_num", "ApplLastSeqNum", base.DEC),
    channel_heartbeat_end_of_channel = ProtoField.uint32("channel_heartbeat.end_of_channel", "EndOfChannel", base.DEC),
    -- Field from ResendRequest
    resend_request_resend_type = ProtoField.uint32("resend_request.resend_type", "ResendType", base.DEC),
    resend_request_channel_no = ProtoField.uint32("resend_request.channel_no", "ChannelNo", base.DEC),
    resend_request_appl_beg_seq_num = ProtoField.int64("resend_request.appl_beg_seq_num", "ApplBegSeqNum", base.DEC),
    resend_request_appl_end_seq_num = ProtoField.int64("resend_request.appl_end_seq_num", "ApplEndSeqNum", base.DEC),
    resend_request_news_id = ProtoField.string("resend_request.news_id", "NewsID"),
    resend_request_resend_status = ProtoField.uint32("resend_request.resend_status", "ResendStatus", base.DEC),
    resend_request_reject_text = ProtoField.string("resend_request.reject_text", "RejectText"),
    -- Field from ChannelStatistics
    channel_statistics_orig_time = ProtoField.int64("channel_statistics.orig_time", "OrigTime", base.DEC),
    channel_statistics_channel_no = ProtoField.uint32("channel_statistics.channel_no", "ChannelNo", base.DEC),
    -- Field from NoMDStreamID
    no_md_stream_id_md_stream_id = ProtoField.string("no_md_stream_id.md_stream_id", "MDStreamID"),
    no_md_stream_id_stock_num = ProtoField.uint32("no_md_stream_id.stock_num", "StockNum", base.DEC),
    no_md_stream_id_trading_phase_code = ProtoField.string("no_md_stream_id.trading_phase_code", "TradingPhaseCode"),
    -- Field from BusinessReject
    business_reject_ref_seq_num = ProtoField.int64("business_reject.ref_seq_num", "RefSeqNum", base.DEC),
    business_reject_ref_msg_type = ProtoField.uint32("business_reject.ref_msg_type", "RefMsgType", base.DEC),
    business_reject_business_reject_ref_id = ProtoField.string("business_reject.business_reject_ref_id", "BusinessRejectRefID"),
    business_reject_business_reject_reason = ProtoField.uint32("business_reject.business_reject_reason", "BusinessRejectReason", base.DEC),
    business_reject_business_reject_text = ProtoField.string("business_reject.business_reject_text", "BusinessRejectText"),
    -- Field from SecurityStatus
    security_status_orig_time = ProtoField.int64("security_status.orig_time", "OrigTime", base.DEC),
    security_status_security_id = ProtoField.string("security_status.security_id", "SecurityID"),
    security_status_security_id_source = ProtoField.string("security_status.security_id_source", "SecurityIDSource"),
    security_status_security_symbol = ProtoField.string("security_status.security_symbol", "SecuritySymbol"),
    -- Field from NoSwitch
    no_switch_security_switch_type = ProtoField.uint32("no_switch.security_switch_type", "SecuritySwitchType", base.DEC),
    no_switch_security_switch_status = ProtoField.uint32("no_switch.security_switch_status", "SecuritySwitchStatus", base.DEC),
    -- Field from Announcement
    announcement_orig_time = ProtoField.int64("announcement.orig_time", "OrigTime", base.DEC),
    announcement_channel_no = ProtoField.uint32("announcement.channel_no", "ChannelNo", base.DEC),
    announcement_news_id = ProtoField.string("announcement.news_id", "NewsID"),
    announcement_headline = ProtoField.string("announcement.headline", "Headline"),
    announcement_news_type = ProtoField.uint32("announcement.news_type", "NewsType", base.DEC),
    announcement_raw_data_format = ProtoField.string("announcement.raw_data_format", "RawDataFormat"),
    announcement_raw_data_length = ProtoField.uint32("announcement.raw_data_length", "RawDataLength", base.DEC),
    announcement_raw_data = ProtoField.string("announcement.raw_data", "RawData"),
    -- Field from SnapshotMarketData
    snapshot_market_data_orig_time = ProtoField.int64("snapshot_market_data.orig_time", "OrigTime", base.DEC),
    snapshot_market_data_channel_no = ProtoField.uint32("snapshot_market_data.channel_no", "ChannelNo", base.DEC),
    snapshot_market_data_md_stream_id = ProtoField.string("snapshot_market_data.md_stream_id", "MDStreamID"),
    snapshot_market_data_security_id = ProtoField.string("snapshot_market_data.security_id", "SecurityID"),
    snapshot_market_data_security_id_source = ProtoField.string("snapshot_market_data.security_id_source", "SecurityIDSource"),
    snapshot_market_data_trading_phase_code = ProtoField.string("snapshot_market_data.trading_phase_code", "TradingPhaseCode"),
    snapshot_market_data_pre_close_px = ProtoField.int64("snapshot_market_data.pre_close_px", "PreClosePx", base.DEC),
    snapshot_market_data_num_trades = ProtoField.int64("snapshot_market_data.num_trades", "NumTrades", base.DEC),
    snapshot_market_data_total_volume_trade = ProtoField.int64("snapshot_market_data.total_volume_trade", "TotalVolumeTrade", base.DEC),
    snapshot_market_data_total_value_trade = ProtoField.int64("snapshot_market_data.total_value_trade", "TotalValueTrade", base.DEC),
    -- Unsupported type: match
    -- Field from ExtendMd010
    -- Field from NoMDEntries
    no_md_entries_md_entry_type = ProtoField.string("no_md_entries.md_entry_type", "MDEntryType"),
    no_md_entries_md_entry_px = ProtoField.int64("no_md_entries.md_entry_px", "MDEntryPx", base.DEC),
    no_md_entries_md_entry_size = ProtoField.int64("no_md_entries.md_entry_size", "MDEntrySize", base.DEC),
    no_md_entries_md_price_level = ProtoField.uint32("no_md_entries.md_price_level", "MDPriceLevel", base.DEC),
    -- Field from NoOrders
    no_orders_order_qty = ProtoField.int64("no_orders.order_qty", "OrderQty", base.DEC),
    -- Field from NoSubTradingPhaseCodes
    no_sub_trading_phase_codes_sub_trading_phase_codes = ProtoField.string("no_sub_trading_phase_codes.sub_trading_phase_codes", "SubTradingPhaseCodes"),
    no_sub_trading_phase_codes_trading_type = ProtoField.uint32("no_sub_trading_phase_codes.trading_type", "TradingType", base.DEC),
    extend_md_010_auction_volume_trade = ProtoField.int64("extend_md_010.auction_volume_trade", "AuctionVolumeTrade", base.DEC),
    extend_md_010_auction_value_trade = ProtoField.int64("extend_md_010.auction_value_trade", "AuctionValueTrade", base.DEC),
    extend_md_010_trade_time = ProtoField.int64("extend_md_010.trade_time", "TradeTime", base.DEC),
    -- Field from ExtendMd020
    -- Field from NoMDEntries
    no_md_entries_md_entry_type = ProtoField.string("no_md_entries.md_entry_type", "MDEntryType"),
    no_md_entries_md_entry_px = ProtoField.int64("no_md_entries.md_entry_px", "MDEntryPx", base.DEC),
    no_md_entries_md_entry_size = ProtoField.int64("no_md_entries.md_entry_size", "MDEntrySize", base.DEC),
    no_md_entries_md_price_level = ProtoField.uint32("no_md_entries.md_price_level", "MDPriceLevel", base.DEC),
    -- Field from NoOrders
    no_orders_order_qty = ProtoField.int64("no_orders.order_qty", "OrderQty", base.DEC),
    -- Field from ExtendMd030
    -- Field from NoMDEntries
    no_md_entries_md_entry_type = ProtoField.string("no_md_entries.md_entry_type", "MDEntryType"),
    no_md_entries_md_entry_px = ProtoField.int64("no_md_entries.md_entry_px", "MDEntryPx", base.DEC),
    -- Field from TickByTickOrderMarketData
    tick_by_tick_order_market_data_orig_time = ProtoField.int64("tick_by_tick_order_market_data.orig_time", "OrigTime", base.DEC),
    tick_by_tick_order_market_data_channel_no = ProtoField.uint32("tick_by_tick_order_market_data.channel_no", "ChannelNo", base.DEC),
    tick_by_tick_order_market_data_appl_seq_num = ProtoField.int64("tick_by_tick_order_market_data.appl_seq_num", "ApplSeqNum", base.DEC),
    tick_by_tick_order_market_data_md_stream_id = ProtoField.string("tick_by_tick_order_market_data.md_stream_id", "MDStreamID"),
    tick_by_tick_order_market_data_security_id = ProtoField.string("tick_by_tick_order_market_data.security_id", "SecurityID"),
    tick_by_tick_order_market_data_security_id_source = ProtoField.string("tick_by_tick_order_market_data.security_id_source", "SecurityIDSource"),
    tick_by_tick_order_market_data_price = ProtoField.int64("tick_by_tick_order_market_data.price", "Price", base.DEC),
    tick_by_tick_order_market_data_order_qty = ProtoField.int64("tick_by_tick_order_market_data.order_qty", "OrderQty", base.DEC),
    tick_by_tick_order_market_data_side = ProtoField.char("tick_by_tick_order_market_data.side", "Side", base.OCT),
    tick_by_tick_order_market_data_transact_time = ProtoField.int64("tick_by_tick_order_market_data.transact_time", "TransactTime", base.DEC),
    -- Unsupported type: match
    -- Field from ExtendOrdMd011
    extend_ord_md_011_ord_type = ProtoField.char("extend_ord_md_011.ord_type", "OrdType", base.OCT),
    extend_ord_md_011_settl_type = ProtoField.char("extend_ord_md_011.settl_type", "SettlType", base.OCT),
    extend_ord_md_011_settl_period = ProtoField.char("extend_ord_md_011.settl_period", "SettlPeriod", base.OCT),
    -- Field from ExtendOrdMd021
    extend_ord_md_021_confirm_id = ProtoField.uint32("extend_ord_md_021.confirm_id", "ConfirmID", base.DEC),
    -- Field from ExtendOrdMd022
    extend_ord_md_022_mm_ord_type = ProtoField.char("extend_ord_md_022.mm_ord_type", "MMOrdType", base.OCT),
    extend_ord_md_022_mm_data_type = ProtoField.char("extend_ord_md_022.mm_data_type", "MMDataType", base.OCT),
    -- Field from ExtendOrdMd023
    extend_ord_md_023_expiration_days = ProtoField.uint32("extend_ord_md_023.expiration_days", "ExpirationDays", base.DEC),
    extend_ord_md_023_expiration_type = ProtoField.uint32("extend_ord_md_023.expiration_type", "ExpirationType", base.DEC),
    -- Field from ExtendOrdMd024
    extend_ord_md_024_confirm_id = ProtoField.uint32("extend_ord_md_024.confirm_id", "ConfirmID", base.DEC),
    extend_ord_md_024_security_type = ProtoField.char("extend_ord_md_024.security_type", "SecurityType", base.OCT),
    extend_ord_md_024_np_ord_type = ProtoField.char("extend_ord_md_024.np_ord_type", "NPOrdType", base.OCT),
    -- Field from TickByTickReportMarketData
    tick_by_tick_report_market_data_channel_no = ProtoField.uint32("tick_by_tick_report_market_data.channel_no", "ChannelNo", base.DEC),
    tick_by_tick_report_market_data_appl_seq_num = ProtoField.int64("tick_by_tick_report_market_data.appl_seq_num", "ApplSeqNum", base.DEC),
    tick_by_tick_report_market_data_md_stream_id = ProtoField.string("tick_by_tick_report_market_data.md_stream_id", "MDStreamID"),
    tick_by_tick_report_market_data_security_id = ProtoField.string("tick_by_tick_report_market_data.security_id", "SecurityID"),
    tick_by_tick_report_market_data_security_id_source = ProtoField.string("tick_by_tick_report_market_data.security_id_source", "SecurityIDSource"),
    tick_by_tick_report_market_data_bid_appl_seq_num = ProtoField.int64("tick_by_tick_report_market_data.bid_appl_seq_num", "BidApplSeqNum", base.DEC),
    tick_by_tick_report_market_data_ask_appl_seq_num = ProtoField.int64("tick_by_tick_report_market_data.ask_appl_seq_num", "AskApplSeqNum", base.DEC),
    tick_by_tick_report_market_data_trade_price = ProtoField.int64("tick_by_tick_report_market_data.trade_price", "TradePrice", base.DEC),
    tick_by_tick_report_market_data_trade_qty = ProtoField.int64("tick_by_tick_report_market_data.trade_qty", "TradeQty", base.DEC),
    tick_by_tick_report_market_data_trade_money = ProtoField.int64("tick_by_tick_report_market_data.trade_money", "TradeMoney", base.DEC),
    tick_by_tick_report_market_data_exec_type = ProtoField.char("tick_by_tick_report_market_data.exec_type", "ExecType", base.OCT),
    tick_by_tick_report_market_data_transact_time = ProtoField.int64("tick_by_tick_report_market_data.transact_time", "TransactTime", base.DEC),
    -- Unsupported type: match
    -- Field from ExtendReportMd011
    extend_report_md_011_settl_period = ProtoField.char("extend_report_md_011.settl_period", "SettlPeriod", base.OCT),
    extend_report_md_011_settl_type = ProtoField.char("extend_report_md_011.settl_type", "SettlType", base.OCT),
    -- Field from ExtendReportMd012
    extend_report_md_012_settl_period = ProtoField.char("extend_report_md_012.settl_period", "SettlPeriod", base.OCT),
    extend_report_md_012_settl_type = ProtoField.char("extend_report_md_012.settl_type", "SettlType", base.OCT),
    -- Field from ExtendReportMd023
    extend_report_md_023_bid_branch_name = ProtoField.string("extend_report_md_023.bid_branch_name", "BidBranchName"),
    extend_report_md_023_offer_branch_name = ProtoField.string("extend_report_md_023.offer_branch_name", "OfferBranchName"),
    -- Field from ExtendReportMd024
    -- Field from BjseMdBinary
    bjse_md_binary_msg_type = ProtoField.uint32("bjse_md_binary.msg_type", "MsgType", base.DEC),
    bjse_md_binary_body_length = ProtoField.uint32("bjse_md_binary.body_length", "BodyLength", base.DEC),
    -- Unsupported type: match
    bjse_md_binary_checksum = ProtoField.uint32("bjse_md_binary.checksum", "Checksum", base.DEC),
}

for _, field in pairs(fields) do
    bjse_md_binary_proto.fields[field] = field
end

local function dissect_logon(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "Logon")
    subtree:add(fields.logon_sender_comp_id, buf(offset, 20))
    offset = offset + 20
    subtree:add(fields.logon_target_comp_id, buf(offset, 20))
    offset = offset + 20
    subtree:le_add(fields.logon_heart_bt_int, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.logon_password, buf(offset, 16))
    offset = offset + 16
    subtree:add(fields.logon_default_appl_ver_id, buf(offset, 32))
    offset = offset + 32
    return offset
end


local function dissect_logout(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "Logout")
    subtree:le_add(fields.logout_session_status, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.logout_text, buf(offset, 200))
    offset = offset + 200
    return offset
end


local function dissect_heartbeat(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "Heartbeat")
    subtree:append_text(" (No Body)")
    return offset
end


local function dissect_channel_heartbeat(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ChannelHeartbeat")
    subtree:le_add(fields.channel_heartbeat_channel_no, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.channel_heartbeat_appl_last_seq_num, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.channel_heartbeat_end_of_channel, buf(offset, 2))
    offset = offset + 2
    return offset
end


local function dissect_resend_request(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ResendRequest")
    subtree:le_add(fields.resend_request_resend_type, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.resend_request_channel_no, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.resend_request_appl_beg_seq_num, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.resend_request_appl_end_seq_num, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.resend_request_news_id, buf(offset, 16))
    offset = offset + 16
    subtree:le_add(fields.resend_request_resend_status, buf(offset, 1))
    offset = offset + 1
    subtree:add(fields.resend_request_reject_text, buf(offset, 16))
    offset = offset + 16
    return offset
end


local function dissect_no_md_stream_id(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "NoMDStreamID")
    subtree:add(fields.no_md_stream_id_md_stream_id, buf(offset, 3))
    offset = offset + 3
    subtree:le_add(fields.no_md_stream_id_stock_num, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.no_md_stream_id_trading_phase_code, buf(offset, 8))
    offset = offset + 8
    return offset
end

local function dissect_channel_statistics(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ChannelStatistics")
    subtree:le_add(fields.channel_statistics_orig_time, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.channel_statistics_channel_no, buf(offset, 2))
    offset = offset + 2
    local channel_statistics_no_md_stream_id_size = buf(offset, 2):le_uint()
    subtree:add("NoMDStreamID Size: ".. channel_statistics_no_md_stream_id_size, buf(offset, 2))
    offset = offset + 2
    for i=1,channel_statistics_no_md_stream_id_size do
        offset = dissect_no_md_stream_id(buf, pinfo, subtree, offset)
        pinfo.cols.info:append(" NoMDStreamID["..i.."]")
    end
    return offset
end


local function dissect_business_reject(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "BusinessReject")
    subtree:le_add(fields.business_reject_ref_seq_num, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.business_reject_ref_msg_type, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.business_reject_business_reject_ref_id, buf(offset, 10))
    offset = offset + 10
    subtree:le_add(fields.business_reject_business_reject_reason, buf(offset, 2))
    offset = offset + 2
    subtree:add(fields.business_reject_business_reject_text, buf(offset, 50))
    offset = offset + 50
    return offset
end


local function dissect_no_switch(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "NoSwitch")
    subtree:le_add(fields.no_switch_security_switch_type, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.no_switch_security_switch_status, buf(offset, 2))
    offset = offset + 2
    return offset
end

local function dissect_security_status(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "SecurityStatus")
    subtree:le_add(fields.security_status_orig_time, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.security_status_security_id, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.security_status_security_id_source, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.security_status_security_symbol, buf(offset, 40))
    offset = offset + 40
    local security_status_no_switch_size = buf(offset, 2):le_uint()
    subtree:add("NoSwitch Size: ".. security_status_no_switch_size, buf(offset, 2))
    offset = offset + 2
    for i=1,security_status_no_switch_size do
        offset = dissect_no_switch(buf, pinfo, subtree, offset)
        pinfo.cols.info:append(" NoSwitch["..i.."]")
    end
    return offset
end


local function dissect_announcement(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "Announcement")
    subtree:le_add(fields.announcement_orig_time, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.announcement_channel_no, buf(offset, 2))
    offset = offset + 2
    subtree:add(fields.announcement_news_id, buf(offset, 16))
    offset = offset + 16
    subtree:add(fields.announcement_headline, buf(offset, 128))
    offset = offset + 128
    subtree:le_add(fields.announcement_news_type, buf(offset, 1))
    offset = offset + 1
    subtree:add(fields.announcement_raw_data_format, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.announcement_raw_data_length, buf(offset, 4))
    offset = offset + 4
    local announcement_raw_data_len = buf(offset, 2):le_uint()
    subtree:add("RawData Len: ".. announcement_raw_data_len, buf(offset, 2))
    offset = offset + 2
    subtree:add(fields.announcement_raw_data, buf(offset, announcement_raw_data_len))
    offset = offset + announcement_raw_data_len
    return offset
end


local function dissect_snapshot_market_data(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "SnapshotMarketData")
    subtree:le_add(fields.snapshot_market_data_orig_time, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.snapshot_market_data_channel_no, buf(offset, 2))
    offset = offset + 2
    local md_stream_id = buf(offset, 3):string()
    subtree:add(fields.snapshot_market_data_md_stream_id, buf(offset, 3))
    offset = offset + 3
    subtree:add(fields.snapshot_market_data_security_id, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.snapshot_market_data_security_id_source, buf(offset, 4))
    offset = offset + 4
    subtree:add(fields.snapshot_market_data_trading_phase_code, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.snapshot_market_data_pre_close_px, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.snapshot_market_data_num_trades, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.snapshot_market_data_total_volume_trade, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.snapshot_market_data_total_value_trade, buf(offset, 8))
    offset = offset + 8
    if md_stream_id == "010" then -- ExtendMd010
        dissect_extend_md_010(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendMd010")
    elseif md_stream_id == "020" then -- ExtendMd020
        dissect_extend_md_020(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendMd020")
    elseif md_stream_id == "030" then -- ExtendMd030
        dissect_extend_md_030(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendMd030")
    end
    return offset
end


local function dissect_no_orders(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "NoOrders")
    subtree:le_add(fields.no_orders_order_qty, buf(offset, 8))
    offset = offset + 8
    return offset
end

local function dissect_no_md_entries(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "NoMDEntries")
    subtree:add(fields.no_md_entries_md_entry_type, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.no_md_entries_md_entry_px, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.no_md_entries_md_entry_size, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.no_md_entries_md_price_level, buf(offset, 2))
    offset = offset + 2
    local no_md_entries_no_orders_size = buf(offset, 2):le_uint()
    subtree:add("NoOrders Size: ".. no_md_entries_no_orders_size, buf(offset, 2))
    offset = offset + 2
    for i=1,no_md_entries_no_orders_size do
        offset = dissect_no_orders(buf, pinfo, subtree, offset)
        pinfo.cols.info:append(" NoOrders["..i.."]")
    end
    return offset
end

local function dissect_no_sub_trading_phase_codes(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "NoSubTradingPhaseCodes")
    subtree:add(fields.no_sub_trading_phase_codes_sub_trading_phase_codes, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.no_sub_trading_phase_codes_trading_type, buf(offset, 1))
    offset = offset + 1
    return offset
end

local function dissect_extend_md_010(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendMd010")
    local extend_md_010_no_md_entries_size = buf(offset, 2):le_uint()
    subtree:add("NoMDEntries Size: ".. extend_md_010_no_md_entries_size, buf(offset, 2))
    offset = offset + 2
    for i=1,extend_md_010_no_md_entries_size do
        offset = dissect_no_md_entries(buf, pinfo, subtree, offset)
        pinfo.cols.info:append(" NoMDEntries["..i.."]")
    end
    local extend_md_010_no_sub_trading_phase_codes_size = buf(offset, 2):le_uint()
    subtree:add("NoSubTradingPhaseCodes Size: ".. extend_md_010_no_sub_trading_phase_codes_size, buf(offset, 2))
    offset = offset + 2
    for i=1,extend_md_010_no_sub_trading_phase_codes_size do
        offset = dissect_no_sub_trading_phase_codes(buf, pinfo, subtree, offset)
        pinfo.cols.info:append(" NoSubTradingPhaseCodes["..i.."]")
    end
    subtree:le_add(fields.extend_md_010_auction_volume_trade, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.extend_md_010_auction_value_trade, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.extend_md_010_trade_time, buf(offset, 8))
    offset = offset + 8
    return offset
end


local function dissect_no_orders(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "NoOrders")
    subtree:le_add(fields.no_orders_order_qty, buf(offset, 8))
    offset = offset + 8
    return offset
end

local function dissect_no_md_entries(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "NoMDEntries")
    subtree:add(fields.no_md_entries_md_entry_type, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.no_md_entries_md_entry_px, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.no_md_entries_md_entry_size, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.no_md_entries_md_price_level, buf(offset, 2))
    offset = offset + 2
    local no_md_entries_no_orders_size = buf(offset, 2):le_uint()
    subtree:add("NoOrders Size: ".. no_md_entries_no_orders_size, buf(offset, 2))
    offset = offset + 2
    for i=1,no_md_entries_no_orders_size do
        offset = dissect_no_orders(buf, pinfo, subtree, offset)
        pinfo.cols.info:append(" NoOrders["..i.."]")
    end
    return offset
end

local function dissect_extend_md_020(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendMd020")
    local extend_md_020_no_md_entries_size = buf(offset, 2):le_uint()
    subtree:add("NoMDEntries Size: ".. extend_md_020_no_md_entries_size, buf(offset, 2))
    offset = offset + 2
    for i=1,extend_md_020_no_md_entries_size do
        offset = dissect_no_md_entries(buf, pinfo, subtree, offset)
        pinfo.cols.info:append(" NoMDEntries["..i.."]")
    end
    return offset
end


local function dissect_no_md_entries(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "NoMDEntries")
    subtree:add(fields.no_md_entries_md_entry_type, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.no_md_entries_md_entry_px, buf(offset, 8))
    offset = offset + 8
    return offset
end

local function dissect_extend_md_030(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendMd030")
    local extend_md_030_no_md_entries_size = buf(offset, 2):le_uint()
    subtree:add("NoMDEntries Size: ".. extend_md_030_no_md_entries_size, buf(offset, 2))
    offset = offset + 2
    for i=1,extend_md_030_no_md_entries_size do
        offset = dissect_no_md_entries(buf, pinfo, subtree, offset)
        pinfo.cols.info:append(" NoMDEntries["..i.."]")
    end
    return offset
end


local function dissect_tick_by_tick_order_market_data(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "TickByTickOrderMarketData")
    subtree:le_add(fields.tick_by_tick_order_market_data_orig_time, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.tick_by_tick_order_market_data_channel_no, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.tick_by_tick_order_market_data_appl_seq_num, buf(offset, 8))
    offset = offset + 8
    local md_stream_id = buf(offset, 3):string()
    subtree:add(fields.tick_by_tick_order_market_data_md_stream_id, buf(offset, 3))
    offset = offset + 3
    subtree:add(fields.tick_by_tick_order_market_data_security_id, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.tick_by_tick_order_market_data_security_id_source, buf(offset, 4))
    offset = offset + 4
    subtree:le_add(fields.tick_by_tick_order_market_data_price, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.tick_by_tick_order_market_data_order_qty, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.tick_by_tick_order_market_data_side, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.tick_by_tick_order_market_data_transact_time, buf(offset, 8))
    offset = offset + 8
    if md_stream_id == "011" then -- ExtendOrdMd011
        dissect_extend_ord_md_011(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendOrdMd011")
    elseif md_stream_id == "021" then -- ExtendOrdMd021
        dissect_extend_ord_md_021(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendOrdMd021")
    elseif md_stream_id == "022" then -- ExtendOrdMd022
        dissect_extend_ord_md_022(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendOrdMd022")
    elseif md_stream_id == "023" then -- ExtendOrdMd023
        dissect_extend_ord_md_023(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendOrdMd023")
    elseif md_stream_id == "024" then -- ExtendOrdMd024
        dissect_extend_ord_md_024(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendOrdMd024")
    end
    return offset
end


local function dissect_extend_ord_md_011(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendOrdMd011")
    subtree:le_add(fields.extend_ord_md_011_ord_type, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.extend_ord_md_011_settl_type, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.extend_ord_md_011_settl_period, buf(offset, 1))
    offset = offset + 1
    return offset
end


local function dissect_extend_ord_md_021(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendOrdMd021")
    subtree:le_add(fields.extend_ord_md_021_confirm_id, buf(offset, 4))
    offset = offset + 4
    return offset
end


local function dissect_extend_ord_md_022(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendOrdMd022")
    subtree:le_add(fields.extend_ord_md_022_mm_ord_type, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.extend_ord_md_022_mm_data_type, buf(offset, 1))
    offset = offset + 1
    return offset
end


local function dissect_extend_ord_md_023(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendOrdMd023")
    subtree:le_add(fields.extend_ord_md_023_expiration_days, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.extend_ord_md_023_expiration_type, buf(offset, 1))
    offset = offset + 1
    return offset
end


local function dissect_extend_ord_md_024(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendOrdMd024")
    subtree:le_add(fields.extend_ord_md_024_confirm_id, buf(offset, 4))
    offset = offset + 4
    subtree:le_add(fields.extend_ord_md_024_security_type, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.extend_ord_md_024_np_ord_type, buf(offset, 1))
    offset = offset + 1
    return offset
end


local function dissect_tick_by_tick_report_market_data(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "TickByTickReportMarketData")
    subtree:le_add(fields.tick_by_tick_report_market_data_channel_no, buf(offset, 2))
    offset = offset + 2
    subtree:le_add(fields.tick_by_tick_report_market_data_appl_seq_num, buf(offset, 8))
    offset = offset + 8
    local md_stream_id = buf(offset, 3):string()
    subtree:add(fields.tick_by_tick_report_market_data_md_stream_id, buf(offset, 3))
    offset = offset + 3
    subtree:add(fields.tick_by_tick_report_market_data_security_id, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.tick_by_tick_report_market_data_security_id_source, buf(offset, 4))
    offset = offset + 4
    subtree:le_add(fields.tick_by_tick_report_market_data_bid_appl_seq_num, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.tick_by_tick_report_market_data_ask_appl_seq_num, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.tick_by_tick_report_market_data_trade_price, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.tick_by_tick_report_market_data_trade_qty, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.tick_by_tick_report_market_data_trade_money, buf(offset, 8))
    offset = offset + 8
    subtree:le_add(fields.tick_by_tick_report_market_data_exec_type, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.tick_by_tick_report_market_data_transact_time, buf(offset, 8))
    offset = offset + 8
    if md_stream_id == "011" then -- ExtendReportMd011
        dissect_extend_report_md_011(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendReportMd011")
    elseif md_stream_id == "012" then -- ExtendReportMd012
        dissect_extend_report_md_012(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendReportMd012")
    elseif md_stream_id == "023" then -- ExtendReportMd023
        dissect_extend_report_md_023(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendReportMd023")
    elseif md_stream_id == "024" then -- ExtendReportMd024
        dissect_extend_report_md_024(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ExtendReportMd024")
    end
    return offset
end


local function dissect_extend_report_md_011(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendReportMd011")
    subtree:le_add(fields.extend_report_md_011_settl_period, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.extend_report_md_011_settl_type, buf(offset, 1))
    offset = offset + 1
    return offset
end


local function dissect_extend_report_md_012(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendReportMd012")
    subtree:le_add(fields.extend_report_md_012_settl_period, buf(offset, 1))
    offset = offset + 1
    subtree:le_add(fields.extend_report_md_012_settl_type, buf(offset, 1))
    offset = offset + 1
    return offset
end


local function dissect_extend_report_md_023(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendReportMd023")
    subtree:add(fields.extend_report_md_023_bid_branch_name, buf(offset, 8))
    offset = offset + 8
    subtree:add(fields.extend_report_md_023_offer_branch_name, buf(offset, 8))
    offset = offset + 8
    return offset
end


local function dissect_extend_report_md_024(buf, pinfo, tree, offset)
    local subtree = tree:add(bjse_md_binary_proto, buf(offset, 1), "ExtendReportMd024")
    subtree:append_text(" (No Body)")
    return offset
end


function bjse_md_binary_proto.dissector(buf, pinfo, tree)
    pinfo.cols.protocol = "bjse_md_binary"
    local offset = 0
    local msg_type = buf(offset, 4):le_uint()
    tree:le_add(fields.bjse_md_binary_msg_type, buf(offset, 4))
    offset = offset + 4
    tree:le_add(fields.bjse_md_binary_body_length, buf(offset, 4))
    offset = offset + 4
    if msg_type == 1 then -- Logon
        dissect_logon(buf, pinfo, tree, offset)
        pinfo.cols.info:set("Logon")
    elseif msg_type == 2 then -- Logout
        dissect_logout(buf, pinfo, tree, offset)
        pinfo.cols.info:set("Logout")
    elseif msg_type == 3 then -- Heartbeat
        dissect_heartbeat(buf, pinfo, tree, offset)
        pinfo.cols.info:set("Heartbeat")
    elseif msg_type == 301000 then -- ChannelHeartbeat
        dissect_channel_heartbeat(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ChannelHeartbeat")
    elseif msg_type == 302000 then -- ResendRequest
        dissect_resend_request(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ResendRequest")
    elseif msg_type == 303000 then -- ChannelStatistics
        dissect_channel_statistics(buf, pinfo, tree, offset)
        pinfo.cols.info:set("ChannelStatistics")
    elseif msg_type == 8 then -- BusinessReject
        dissect_business_reject(buf, pinfo, tree, offset)
        pinfo.cols.info:set("BusinessReject")
    elseif msg_type == 304000 then -- SecurityStatus
        dissect_security_status(buf, pinfo, tree, offset)
        pinfo.cols.info:set("SecurityStatus")
    elseif msg_type == 305000 then -- Announcement
        dissect_announcement(buf, pinfo, tree, offset)
        pinfo.cols.info:set("Announcement")
    elseif msg_type == 306001 then -- SnapshotMarketData
        dissect_snapshot_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("SnapshotMarketData")
    elseif msg_type == 306002 then -- SnapshotMarketData
        dissect_snapshot_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("SnapshotMarketData")
    elseif msg_type == 306003 then -- SnapshotMarketData
        dissect_snapshot_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("SnapshotMarketData")
    elseif msg_type == 307011 then -- TickByTickOrderMarketData
        dissect_tick_by_tick_order_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("TickByTickOrderMarketData")
    elseif msg_type == 307021 then -- TickByTickOrderMarketData
        dissect_tick_by_tick_order_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("TickByTickOrderMarketData")
    elseif msg_type == 307022 then -- TickByTickOrderMarketData
        dissect_tick_by_tick_order_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("TickByTickOrderMarketData")
    elseif msg_type == 307023 then -- TickByTickOrderMarketData
        dissect_tick_by_tick_order_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("TickByTickOrderMarketData")
    elseif msg_type == 307024 then -- TickByTickOrderMarketData
        dissect_tick_by_tick_order_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("TickByTickOrderMarketData")
    elseif msg_type == 308011 then -- TickByTickReportMarketData
        dissect_tick_by_tick_report_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("TickByTickReportMarketData")
    elseif msg_type == 308012 then -- TickByTickReportMarketData
        dissect_tick_by_tick_report_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("TickByTickReportMarketData")
    elseif msg_type == 308023 then -- TickByTickReportMarketData
        dissect_tick_by_tick_report_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("TickByTickReportMarketData")
    elseif msg_type == 308024 then -- TickByTickReportMarketData
        dissect_tick_by_tick_report_market_data(buf, pinfo, tree, offset)
        pinfo.cols.info:set("TickByTickReportMarketData")
    end
    tree:le_add(fields.bjse_md_binary_checksum, buf(offset, 4))
    offset = offset + 4
end


local tcp_table = DissectorTable.get("tcp.port")
tcp_table:add(8080, bjse_md_binary_proto)
